### ISSUE TITLE
UI doesn't show all training data

### ISSUE THREAD

**Issue by michaelnatkin** [vanna-ai/vanna#183] opened 2024-01-24 06:12 UTC
I've trained on several hundred items, but the UI only shows the first 25. Confirmed that even after I add another one in the UI, it says there are 25, and if I delete one - still stays 25 :). 

<img width="1315" alt="image" src="https://github.com/vanna-ai/vanna/assets/2817245/98e448bc-8e8c-4875-a56f-817cf768a1ee">

**Comment by michaelnatkin** [comment] 2024-01-24 06:13
This is vanna-flask, specifically.

**Comment by michaelnatkin** [comment] 2024-01-24 06:14
Ah, here's the offending code in app.py

 "df": df.head(25).to_json(orient='records'),

**Comment by zainhoda** [comment] 2024-01-25 14:53
Thanks -- this is a duplicate of this issue:
https://github.com/vanna-ai/vanna/issues/182

**Closed** 2024-02-23 14:07 UTC
