### ISSUE TITLE
It takes 3 minutes to answer a question.

### ISSUE THREAD

**Issue by lokwingfai** [vanna-ai/vanna#552] opened 2024-07-12 10:23 UTC
**Describe the bug**
This is not a bug, but there are no other headings (e.g. usage) to select for this issue.
The response time is long, there are any settings that can make it respond faster.

**To Reproduce**
1. Go to 'New Question'
2. Input Question 'Please generate SQL Server SQL statements from store information whose address start with "紅磡"'

**Expected behavior**
response with 8s to 1m.

**Error logs/Screenshots**
question ask at 5:15:42
<img width="1280" alt="Screenshot 2024-07-12 at 5 15 42 PM" src="https://github.com/user-attachments/assets/2551f2db-4b72-4bc2-8eda-0d8d7affaae5">
Response at 15.18.47
<img width="1280" alt="Screenshot 2024-07-12 at 5 18 47 PM" src="https://github.com/user-attachments/assets/63af33c8-a610-4022-a585-97d5d0c81451">

**Desktop (please complete the following information where):**
 - OS: [Ubuntu]
 - Version: [22.04.4 LTS]
 - Python: [3.10.12]
 - Vanna: [2.8.0]
 - DataBase [Sql Server]
 - Ollama [llama3:70b]

**Additional context**
app.py
//--{{ START
from vanna.ollama import Ollama
from vanna.chromadb import ChromaDB_VectorStore

class MyVanna(ChromaDB_VectorStore, Ollama):
    def __init__(self, config=None):
        ChromaDB_VectorStore.__init__(self, config=config)
        Ollama.__init__(self, config=config)

vn = MyVanna(config={'model': 'llama3:70b'})

vn.connect_to_mssql(odbc_conn_str='DRIVER={ODBC Driver 17 for SQL Server};SERVER=172.25.23.130,1433;DATABASE=STDV85;UID=STDV85;PWD=XXX') # You can use the ODBC connection string here

from vanna.flask import VannaFlaskApp
app = VannaFlaskApp(vn,allow_llm_to_see_data=True,chart=False)
app.run()

//--}} END

Hardware
//--{{ START
H/W path           Device     Class          Description
========================================================
                              system         MS-7A62 (Default string)
/0                            bus            B250 GAMING M3 (MS-7A62)
/0/0                          memory         64KiB BIOS
/0/3c                         memory         32GiB System Memory
/0/3c/0                       memory         [empty]
/0/3c/1                       memory         16GiB DIMM DDR4 Synchronous Unbuffe
/0/3c/2                       memory         [empty]
/0/3c/3                       memory         16GiB DIMM DDR4 Synchronous Unbuffe
/0/42                         memory         256KiB L1 cache
/0/43                         memory         1MiB L2 cache
/0/44                         memory         6MiB L3 cache
/0/45                         processor      Intel(R) Core(TM) i5-6400 CPU @ 2.7
/0/100                        bridge         Xeon E3-1200 v5/E3-1500 v5/6th Gen 
/0/100/1                      bridge         6th-10th Gen Core Processor PCIe Co
/0/100/1/0                    display        NVIDIA Corporation
/0/100/1/0.1       card0      multimedia     NVIDIA Corporation
/0/100/1/0.1/0     input5     input          HDA NVidia HDMI/DP,pcm=3
/0/100/1/0.1/1     input6     input          HDA NVidia HDMI/DP,pcm=7
/0/100/1/0.1/2     input7     input          HDA NVidia HDMI/DP,pcm=8
/0/100/1/0.1/3     input8     input          HDA NVidia HDMI/DP,pcm=9
/0/100/8                      generic        Xeon E3-1200 v5/v6 / E3-1500 v5 / 6
/0/100/14                     bus            200 Series/Z370 Chipset Family USB 
/0/100/14/0        usb1       bus            xHCI Host Controller
/0/100/14/0/1      input3     input          Logitech USB Optical Mouse
/0/100/14/0/2      input4     input          CHICONY USB Keyboard
/0/100/14/1        usb2       bus            xHCI Host Controller
/0/100/14.2                   generic        200 Series PCH Thermal Subsystem
/0/100/16                     communication  200 Series PCH CSME HECI #1
/0/100/17          scsi5      storage        200 Series PCH SATA controller [AHC
/0/100/17/0.0.0    /dev/sda   disk           1TB CT1000MX500SSD1
/0/100/17/0.0.0/1  /dev/sda1  volume         511MiB Windows FAT volume
/0/100/17/0.0.0/2  /dev/sda2  volume         931GiB EXT4 volume
/0/100/1c                     bridge         200 Series PCH PCI Express Root Por
/0/100/1c/0                   bus            ASM1142 USB 3.1 Host Controller
/0/100/1c/0/0      usb3       bus            xHCI Host Controller
/0/100/1c/0/1      usb4       bus            xHCI Host Controller
/0/100/1c.7                   bridge         200 Series PCH PCI Express Root Por
/0/100/1c.7/0      enp3s0     network        Killer E2500 Gigabit Ethernet Contr
/0/100/1f                     bridge         200 Series PCH LPC Controller (B250
/0/100/1f/0                   system         PnP device PNP0c02
/0/100/1f/1                   system         PnP device PNP0c02
/0/100/1f/2                   system         PnP device PNP0c02
/0/100/1f/3                   system         PnP device PNP0b00
/0/100/1f/4                   generic        PnP device INT3f0d
/0/100/1f/5                   system         PnP device PNP0c02
/0/100/1f/6                   system         PnP device PNP0c02
/0/100/1f/7                   system         PnP device PNP0c02
/0/100/1f/8                   system         PnP device PNP0c02
/0/100/1f.2                   memory         Memory controller
/0/100/1f.4                   bus            200 Series/Z370 Chipset Family SMBu
/1                            power          To Be Filled By O.E.M.
/2                 /dev/fb0   display        EFI VGA
/3                 input0     input          Sleep Button
/4                 input1     input          Power Button
/5                 input2     input          Power Button
//--}} END

**Comment by zainhoda** [comment] 2024-07-12 14:04
We have no control over how long Ollama takes on your machine

**Comment by andreped** [comment] 2024-08-01 14:04
@lokwingfai Looks like you are on macOS. I had similar issues just doing simple chat completions. Did you try using a more quantised model? That should definitely help runtime.

Google just released a really high-performing 2B param model `gemma-2` that I would encourage you to try. See here:
https://huggingface.co/google/gemma-2b

There are also several `llama-3` variants that you could try here:
https://huggingface.co/QuantFactory/Meta-Llama-3-8B-Instruct-GGUF

Otherwise, my personal local favourite are the `Qwen`-models. Recently `qwen-2` was released, also with very small models. I would check that out as well:
https://huggingface.co/collections/Qwen/qwen2-6659360b33528ced941e557f

**Comment by lokwingfai** [comment] 2024-08-02 02:56
@andreped Thanks for your suggestion, I am using mistral now and the performance is acceptable.

**Comment by andreped** [comment] 2024-08-02 06:43
> @andreped Thanks for your suggestion, I am using mistral now and the performance is acceptable.

@lokwingfai Great to hear that you resolved the issue. Would be great if you could close this issue then, as the issue is resolved :]

**Closed** 2024-08-06 09:32 UTC
