### ISSUE TITLE
MistralAPIStatusException: Cannot stream response. Status: 429

### ISSUE THREAD

**Issue by ttkrpink** [vanna-ai/vanna#177] opened 2024-01-23 01:18 UTC
I put one training question/sql pair into the model. 
I trained the model using vn.train(). 
The vn.ask return with 429 error.

![1705971871593](https://github.com/vanna-ai/vanna/assets/2522889/3cc196c0-1ea8-4760-87ca-bf920b8291a6)

**Comment by zainhoda** [comment] 2024-01-23 01:48
Do you have a Mistral account? Currently the configuration for Mistral requires a Mistral API key

**Comment by ttkrpink** [comment] 2024-01-23 02:58
I did have the API key.


```
API_Mistral = "xxxxxxxxxxxxxxxxxxxxxx"
API_Vanna ="xxxxxxxxxxxxxxxxxxxxxx"

from vanna.chromadb.chromadb_vector import ChromaDB_VectorStore
from vanna.mistral.mistral import Mistral

Database = './database.sqlite'
class MyVanna(ChromaDB_VectorStore, Mistral):
    def __init__(self, config=None):
        ChromaDB_VectorStore.__init__(self, config=config)
        Mistral.__init__(self, config={'api_key': API_Mistral, 'model': 'mistral-tiny'})

vn = MyVanna()
```

**Comment by zainhoda** [comment] 2024-03-14 02:54
Closing this issue as non-reproducible. Our integration test runs against Mistral on every merge and nobody else has reported this issue:

https://github.com/vanna-ai/vanna/actions/runs/8180364867/job/22368242743#step:5:35

**Closed by zainhoda** 2024-03-14 02:54 UTC

**Comment by varunsingh3000** [comment] 2024-04-01 21:21
This happened to me because my monthly usage limit had reached on the platform. Increasing the limit fixed it.

**Comment by zainhoda** [comment] 2024-04-01 21:36
Thanks @varunsingh3000 and @ttkrpink -- This type of error comes directly from the API provider (Mistral). I think the right thing to do is to keep the raw error as is. It's really Mistral that should provide more context about the error via their package: https://github.com/mistralai/client-python

I think once we get into the business of "interpreting" API errors, it's going to get unmanageable for us very quickly, especially if the underlying Mistral package changes its error handling/messages.
